# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Deploy this DaemonSet to disable hyper-threading on the nodes with the
# "cloud.google.com/gke-smt-disabled=true" label.
#
# WARNING: Disabling hyper-threading might have severe performance impact on
# your clusters and application. Please ensure that this is acceptable before
# deploying this to your production clusters.
#
# WARNING: Disabling hyper-threading requires node reboot. Therefore, in order
# to avoid disrupting your workloads, it is recommended to create a new node
# pool with the "cloud.google.com/gke-smt-disabled=true" label in your cluster,
# deploy the DaemonSet to disable hyper-threading in that node pool, and then
# migrate your workloads to the new node pool.

#
# NOTE:
# It's recommended to use the --threads-per-core flag on the node-pool to
# configure SMT setting on nodes.
# https://cloud.google.com/kubernetes-engine/docs/how-to/configure-smt
#

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disable-smt
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: disable-smt
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: disable-smt
    spec:
      tolerations:
      - operator: Exists
      volumes:
      - name: host
        hostPath:
          path: /
      hostPID: true
      initContainers:
      - name: smt
        image: bash
        command:
        - /usr/local/bin/bash
        - -c
        - |
          set -euo pipefail
          echo "SMT is set to $(cat /host/sys/devices/system/cpu/smt/control)"
          echo "Setting SMT to off"
          echo -n "off" > /host/sys/devices/system/cpu/smt/control
          echo "Restarting Kubelet..."
          chroot /host nsenter --target=1 --all -- systemctl restart kubelet.service
        volumeMounts:
        - name: host
          mountPath: /host
        resources:
          requests:
            memory: 5Mi
            cpu: 5m
        securityContext:
          privileged: true
      containers:
      - image: gcr.io/google-containers/pause:3.2
        name: pause
      # Ensures that the pods will only run on the nodes having the certain
      # label.
      nodeSelector:
        "cloud.google.com/gke-smt-disabled": "true"
